### ISSUE TITLE
How to execute the pattern once

### ISSUE THREAD

**Issue by ghost** [RobTillaart/PulsePattern#11]
Is there a way to execute the pattern only once?

**Comment by RobTillaart** [comment]
At the moment there is no "real" support for  ONCE mode, but I think it is not to difficult to include it.
I will create a develop branch soon (its now 20:00 over here) to give it a try.

The idea is to extend the class with a PP_ONCE and a PP_CONT flag, in a way that's backwards compatible.

**Comment by RobTillaart** [comment]
@Mark-81 
Created - https://github.com/RobTillaart/PulsePattern/tree/develop branch.
This adds a times parameter to **start(uint32_t times = PP_CONTINUOUS)** in which you can define the number of repeats. 
So if you want it ONCE just add 1 as parameter for start.

Note that this code only works on AVR (tested on UNO only).

Can you please verify the develop branch solves your needs?
I can create a ```#define PP_ONCE   1``` to make it ONCE more explicit.

**Comment by RobTillaart** [comment]
@Mark-81
```#define PP_ONCE   1``` added (for convenience).

**Comment by RobTillaart** [comment]
@Mark-81 
tests showed no problems, so running once is now supported.

**Comment by ghost** [comment]
Great! Thank you very much for your support!

**Comment by RobTillaart** [comment]
@Mark-81 
Can you confirm it works?
